export const BLOG_FORM_DATA = "BLOG_FORM_DATA";
export const SHOW_BLOG = "SHOW_BLOG"
export const SHOW_BLOG_FROM_BLOG_COMPONENT = "SHOW_BLOG_FROM_BLOG_COMPONENT";
export const LOGOUT = "LOGOUT";
export const VIEW_BLOG_POST_SELECT = "VIEW_BLOG_POST_SELECT";
export const DATA_COUNT_LOADER = "DATA_COUNT_LOADER";
export const DATA_FETCH = "DATA_FETCH";
export const INITIAL_DATA_FETCH = "INITIAL_DATA_FETCH"